apiVersion: v1
kind: Secret
metadata:
  name: external-postgres-configuration-controller
  namespace: sulabh-postgres
type: Opaque
stringData:
  type: unmanaged
  host: postgres-test-rw
  port: "5432"
  database: aap_controller
  username: aap
  password: aap12345

