apiVersion: v1
kind: Secret
metadata:
  name: external-postgres-configuration-eda
  namespace: postgres-dr
type: Opaque
stringData:
  type: unmanaged
  host: postgres-dr-rw
  port: "5432"
  database: aap_eda
  username: aap
  password: aap12345

